spring:
  application:
    name: gmail-reply-assistant-service
  ai:
    openai:
      api-key: <GROQ_API_KEY>
      base-url: https://api.groq.com/openai
      chat:
        options:
          model: llama-3.3-70b-versatile
          temperature: 0.7
server:
  port: 8080


