spring:
  application:
    name: gmail-reply-assistant-service
  ai:
    openai:
      api-key: ${GROQ_API_KEY}
      base-url: https://api.groq.com/openai
      chat:
        options:
          model: ${MODEL_NAME}
          temperature: 0.7
server:
  port: 8080


